spring:
  jpa:
    show-sql: true
rabbitmq:
  ledger:
    creditaccount:
      queue: ledger.creditaccount.queue
    debitaccount:
      queue: ledger.debitaccount.queue
    query:
      loan:
        id:
          queue: ledger.query.loan.id.queue
