rabbitmq:
  host: localhost
  port: 5672
  virtual-host: /
  password: guest
  username: guest
  exchange: merchloan.exchange
  ledger:
    credittoloan:
      queue: ledger.credittoloan.queue
      routingkey: ledger.credittoloan.routingkey
    debitfromloan:
      queue: ledger.debitfromloan.queue
      routingkey: ledger.debitfromloan.routingkey
  servicerequest:
    routingkey: servicerequest.routingkey
jpa:
  show-sql: true