services:
  accountsdb:
    image: accountsdb
    container_name: accountsdb
    networks:
      - merchloan-internal
  statementdb:
    image: statementdb
    container_name: statementdb
    networks:
      - merchloan-internal
  businessdate:
    image: businessdate
    environment:
      rabbitmq.host: rabbitmq
      redis.host: redis
    ports:
      - "8100:8100"
    networks:
      - merchloan-internal
      - merchloan-rest
    depends_on:
      - redis
      - rabbitmq
  servicerequest:
    image: servicerequest
    environment:
      rabbitmq.host: rabbitmq
      redis.host: redis
    ports:
      - "8080:8080"
    networks:
      - merchloan-internal
      - merchloan-rest
    depends_on:
      - redis
      - rabbitmq
  query:
    image: query
    environment:
      rabbitmq.host: rabbitmq
    ports:
      - "8090:8090"
    networks:
      - merchloan-internal
      - merchloan-rest
    depends_on:
      - rabbitmq
  statement1:
    image: statement
    environment:
      rabbitmq.host: rabbitmq
      statementdb.host: statementdb
    networks:
      - merchloan-internal
    depends_on:
      - statementdb
      - rabbitmq
  statement2:
    image: statement
    environment:
      rabbitmq.host: rabbitmq
      statementdb.host: statementdb
    networks:
      - merchloan-internal
    depends_on:
      - statementdb
      - rabbitmq
  statement3:
    image: statement
    environment:
      rabbitmq.host: rabbitmq
      statementdb.host: statementdb
    networks:
      - merchloan-internal
    depends_on:
      - statementdb
      - rabbitmq
  accounts1:
    image: accounts
    environment:
      rabbitmq.host: rabbitmq
      accountsdb.host: accountsdb
    networks:
      - merchloan-internal
    depends_on:
      - accountsdb
      - rabbitmq
  accounts2:
    image: accounts
    environment:
      rabbitmq.host: rabbitmq
      accountsdb.host: accountsdb
    networks:
      - merchloan-internal
    depends_on:
      - accountsdb
      - rabbitmq
  accounts3:
    image: accounts
    environment:
      rabbitmq.host: rabbitmq
      accountsdb.host: accountsdb
    networks:
      - merchloan-internal
    depends_on:
      - accountsdb
      - rabbitmq
  redis:
    image: redis
    hostname: redis
    container_name: redis
    networks:
      - merchloan-internal
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
    networks:
      - merchloan-internal
networks:
# The presence of these objects is sufficient to define them
  merchloan-internal: {}
  merchloan-rest: {}