spring:
  jpa:
    show-sql: true
rabbitmq:
  statement:
    statement:
      queue: statement.statement.queue
    closestatement:
      queue: statement.closestatement.queue
    query:
      statement:
        queue: statement.query.statement.queue
      mostrecentstatement:
        queue: statement.query.mostrecentstatement.queue
      statements:
        queue: statement.query.statements.queue
logging:
  level:
    org:
      springframework:
        orm:
          jpa: debug

