spring:
  jpa:
    show-sql: true
rabbitmq:
  register:
    creditloan:
      queue: register.creditloan.queue
    debitloan:
      queue: register.debitloan.queue
    query:
      loan:
        id:
          queue: register.query.loan.id.queue
