spring:
  jpa:
    show-sql: false
rabbitmq:
  register:
    fundloan:
      queue: register.fundloan.queue
    creditloan:
      queue: register.creditloan.queue
    debitloan:
      queue: register.debitloan.queue
    statementheader:
      queue: register.statementheader.queue
    billingcyclecharge:
      queue: register.billingcyclecharge.queue
    closeloan:
      queue: register.closeloan.queue
    query:
      loan:
        id:
          queue: register.query.loan.id.queue
logging:
  level:
    org:
      springframework:
        orm:
          jpa: debug
