spring:
  jpa:
    show-sql: true
    open-in-view: false
rabbitmq:
  servicerequest:
    queue: servicerequest.queue
    checkrequest:
      queue: servicerequest.checkrequest.queue
    billloan:
      queue: servicerequest.billloan.queue
    query:
      id:
        queue: servicerequest.querybyid.queue
