spring:
  jpa:
    show-sql: true
rabbitmq:
  account:
    createaccount:
      queue: account.createaccount.queue
    funding:
      queue: account.funding.queue
    query:
      account:
        id:
          queue: account.query.account.id.queue
      loan:
        id:
          queue: account.query.loan.id.queue